[package]
name = "mongo-derive-example"
version = "0.0.0"
authors = ["Haikel Ouaghrem <haikelben@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
bson = "2.10.0"
mongodb = "2.8.2"
serde = { version = "1.0", features = ["derive"] }
tokio = "1.43.0"
mongo_derive = { path = "./../.." }
